import {
  cosmos,
  signAmino,
  signAndSendTransaction,
  signDirect,
  sendTransaction,
  requestAccount,
  getSupportedChainIds,
  addCosmosChain,
  signMessage,
  verifyMessage,
  on,
  off,
  CosmosSignAndSendTransactionProps,
} from './cosmos';
import {
  CosmosSignAminoDoc,
  CosmosSignDirectDoc,
  CosmosRequestAccountResponse,
  CosmosSignOptions,
  CosmosSignDirectResponse,
  CosmosSignAminoResponse,
  CosmosSendTransactionResponse,
  CosmosSignMessageResponse,
  toUint8Array,
  toHexString,
} from '@cosmostation/wallets';

const cosmosFunctions = {
  on,
  off,
  signAmino,
  signAndSendTransaction,
  signDirect,
  sendTransaction,
  requestAccount,
  getSupportedChainIds,
  addCosmosChain,
  signMessage,
  verifyMessage,
};

export {
  cosmos,
  cosmosFunctions,
  CosmosSignAndSendTransactionProps,
  CosmosSignAminoDoc,
  CosmosSignDirectDoc,
  CosmosRequestAccountResponse,
  CosmosSignOptions,
  CosmosSignDirectResponse,
  CosmosSignAminoResponse,
  CosmosSendTransactionResponse,
  CosmosSignMessageResponse,
  toUint8Array,
  toHexString,
};
